# MySQL Database Configuration (Cloud / Local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/movie_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# Other application properties (unrelated to datasource)
server.port=8080
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
enable.swagger.plugin=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
springdoc.swagger-ui.path=/api-docs
spring.servlet.multipart.max-request-size=100MB
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=movie-booking