export const UNIQUE_INDIAN_MOVIES: any[] = [
  { title: 'Dangal', duration: 161, genre: 'Action' },
  { title: 'Drishyam', duration: 160, genre: 'Crime' },
  { title: 'Gol Maal', duration: 144, genre: 'Comedy' },
  { title: 'Jaane Bhi Do Yaaro', duration: 132, genre: 'Comedy' },
  { title: 'Chupke Chupke', duration: 127, genre: 'Comedy' },
  { title: 'A Wednesday', duration: 104, genre: 'Crime' },
  { title: 'Talvar', duration: 132, genre: 'Biography' },
  { title: 'Paan Singh Tomar', duration: 135, genre: 'Action' },
  { title: 'Queen', duration: 146, genre: 'Adventure' },
  { title: 'Black', duration: 122, genre: 'Drama' },
  { title: 'Udaan', duration: 134, genre: 'Drama' },
  { title: 'Jo Jeeta Wohi Sikandar', duration: 174, genre: 'Comedy' },
  { title: 'Gangs of Wasseypur', duration: 320, genre: 'Action' },
  { title: 'Chak De! India', duration: 153, genre: 'Drama' },
  { title: 'Swades: We, the People', duration: 210, genre: 'Drama' },
  { title: 'OMG: Oh My God!', duration: 125, genre: 'Comedy' },
  { title: 'Bhaag Milkha Bhaag', duration: 186, genre: 'Action' },
  { title: 'Kahaani', duration: 122, genre: 'Drama' },
  { title: 'Shahid', duration: 129, genre: 'Biography' },
  { title: 'Dil Chahta Hai', duration: 183, genre: 'Comedy' },
  { title: 'Satya', duration: 170, genre: 'Action' },
  { title: 'PK', duration: 153, genre: 'Comedy' },
  { title: 'Lagaan', duration: 224, genre: 'Adventure' },
  { title: 'Sarfarosh', duration: 174, genre: 'Action' },
  { title: 'Omkara', duration: 155, genre: 'Action' },
  { title: 'Dilwale Dulhania Le Jayenge', duration: 189, genre: 'Comedy' },
  { title: 'Zindagi Na Milegi Dobara', duration: 155, genre: 'Adventure' },
  { title: 'Barfi!', duration: 151, genre: 'Adventure' },
  { title: 'Ugly', duration: 128, genre: 'Crime' },
  { title: 'Haider', duration: 160, genre: 'Action' },
  { title: 'Deewaar', duration: 174, genre: 'Action' },
  { title: 'Masaan', duration: 109, genre: 'Drama' },
  { title: 'Athadu', duration: 172, genre: 'Action' },
  { title: 'Lucia', duration: 135, genre: 'Drama' },
  { title: 'Company', duration: 155, genre: 'Action' },
  { title: 'Special Chabbis', duration: 144, genre: 'Action' },
  { title: 'Manjhi: The Mountain Man', duration: 120, genre: 'Biography' },
  { title: 'Vaastav: The Reality', duration: 145, genre: 'Crime' },
  { title: 'Bajrangi Bhaijaan', duration: 163, genre: 'Action' },
  { title: 'Ankhon Dekhi', duration: 107, genre: 'Comedy' },
  { title: 'Bahubali: The Beginning', duration: 159, genre: 'Action' },
  { title: 'Kal Ho Naa Ho', duration: 186, genre: 'Comedy' },
  { title: 'Johnny Gaddaar', duration: 135, genre: 'Crime' },
  { title: 'Baby', duration: 159, genre: 'Action' },
  { title: 'Lakshya', duration: 186, genre: 'War' },
  { title: 'My Name Is Khan', duration: 165, genre: 'Adventure' },
  { title: 'Gangaajal', duration: 157, genre: 'Crime' },
  { title: 'English Vinglish', duration: 134, genre: 'Comedy' },
  { title: 'Border', duration: 176, genre: 'Action' },
  { title: 'Manam', duration: 163, genre: 'Comedy' },
  { title: 'Oye Lucky! Lucky Oye!', duration: 125, genre: 'Comedy' },
  { title: 'RangiTaranga', duration: 149, genre: 'Adventure' },
  { title: 'The Lunchbox', duration: 104, genre: 'Drama' },
  { title: 'Kapoor & Sons', duration: 132, genre: 'Comedy' },
  { title: 'Samsara', duration: 145, genre: 'Adventure' },
];
